spring.application.name=carsharing

spring.datasource.url=jdbc:postgresql://localhost:5432/carsharingdb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.mvc.hiddenmethod.filter.enabled=true

spring.mail.host=smtp.gmail.com

spring.mail.port=587
spring.mail.username=andrey.l.evseev@gmail.com
spring.mail.password=thua mzyu wqbb ueym 
spring.mail.properties.smtp.auth=true
spring.mail.properties.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
