spring.application.name=flux-carsharing
server.port=8181

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/carsharingdb
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres
spring.r2dbc.pool.enabled=true
spring.r2dbc.initialization-mode=always
